name: 'IntelliJ IDEA source formatter'
description: 'Check and format source files using IntelliJ IDEA CE'
inputs:
  settings-file:
    description: 'Path to the IntelliJ settings file'
    required: true
  file-mask:
    description: 'File mask'
    required: true
  additional-options:
    description: 'Additional format.sh options'
    required: false
    default: null
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.file-mask }}
    - ${{ inputs.additional-options }}
    - ${{ inputs.settings-file }}
